
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => Array.from(r.querySelectorAll(s));
const taskList = $('#taskList');
const modal = $('#modal');
const openModalBtn = $('#openModalBtn');
const cancelBtn = $('#cancelBtn');
const taskForm = $('#taskForm');
const searchInput = $('#searchInput');
const statusFilter = $('#statusFilter');
const priorityFilter = $('#priorityFilter');
const sortSelect = $('#sortSelect');
const selectAllBtn = $('#selectAll');
const clearSelectionBtn = $('#clearSelection');
const deleteSelectedBtn = $('#deleteSelected');
const clearDoneBtn = $('#clearDone');
const statTotal = $('#statTotal');
const statTodo = $('#statTodo');
const statDoing = $('#statDoing');
const statDone = $('#statDone');
const statP1 = $('#statP1');
const statP2 = $('#statP2');
const statP3 = $('#statP3');
let tasks = JSON.parse(localStorage.getItem('todo.enhanced.v1') || '[]');
let editingId = null;
let selected = new Set();
